description: >
  Greetings, I'm Kuat! Software Engineer, Arrow Stomper, Competitive Gamer, Food Enthusiast. 
  Don't be shy, just click the link to know me more! :)
keywords: 'kuat, hadianto, kuat hadianto'